### ISSUE TITLE
Health bar not distinguishable enough

### ISSUE THREAD

**Issue by jakepruitt** [collectivereaction/Nightmare#4]
One of the users commented that the healthbar's color made it hard to tell what the current health was, or when it changed. Possibly adding the animation would help this, or move the position of the bar higher up on the screen

**Comment by hai1337** [comment]
Changed the background of the slider to bright pink with the same white foreground as well as making the health bar taller. So far it looks good but I want feedback before closing.

**Comment by hai1337** [comment]
Health bar is good to go. Consider adding particles to the health bar to let the player know the health has changed, for example, when the health is increased, the health bar sparkles green.

**Comment by jakepruitt** [comment]
Thanks @hmthomas93
